### ISSUE TITLE
No code present

### ISSUE THREAD

**Issue by ff6347** [IsabellHerzog/processing-sketch#1]
I isabell. If you don't push your code to the repo I cant take a look. :cry:

**Comment by IsabellHerzog** [comment]
Hey Fabian,
der Ordner müsste eigentlich seit 20h unter folgenden Namen zu finden sein: iherzog_sketch_01.pde 

github.com/IsabellHerzog/processing-sketch
Ein Freund meinte, er hatte Einsicht. Als Collaborator hab ich dich auch hinzugefügt.

Grüße Isabell

Von meinem iPhone gesendet

**Comment by ff6347** [comment]
Dann Zeig mir doch mal nen Link. https://github.com/IsabellHerzog/processing-sketch
Hier ist er nicht.

**Comment by IsabellHerzog** [comment]
https://github.com/IsabellHerzog/processing-sketch/commit/f7f6f97fbc44d4645636a0b63ae6448e182a6882

ich hab das wie deine Variante in der Werkstatt genannt 😳
Ansonsten zeig ich dir am Mittwoch.

Von meinem iPhone gesendet

> Am 10.11.2014 um 13:10 schrieb Fabian Morón Zirfas notifications@github.com:
> 
> Dann Zeig mir doch mal nen Link. https://github.com/IsabellHerzog/processing-sketch
> Hier ist er nicht.
> 
> —

**Comment by ff6347** [comment]
Du hast es wieder gelöscht. :-)

**Comment by ff6347** [comment]
So. Ist wieder da.

**Comment by IsabellHerzog** [comment]
stimmt die aktuelle Version ist nicht drin. Ich habe aber evtl einen Ansatz und Frage dich besser am Mittwoch. 😳 ...Bevor es wieder in einer unzähligen Anzahl an Mails endet.  
Oder ich aktualisiere sie erstmal, sobald ich meinen Rechner vor mir habe. Ich verstehe manchmal nicht wie diese ständigen Probleme bei mir entstehen... wo im ersten Moment doch alles so klar schien. sorry Fabian. 
Beste Grüße Isabell 

Von meinem iPhone gesendet
